name: 🐛 Bug Report - Something's Not Working Right
description: Report a bug or issue with the fitness tracker
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🏋️‍♀️
        This helps make the fitness tracker better for everyone.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you expected to happen and what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: I expected the app to...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here...

  - type: dropdown
    id: fitness-area
    attributes:
      label: Which fitness feature is affected?
      description: Which part of the fitness tracker is having issues?
      options:
        - Activity Tracking
        - User Profile
        - Goals & Progress
        - Dashboard
        - Database Connection
        - API Endpoints
        - UI/Design
        - Other
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: Chrome, Firefox, Safari, etc.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of the fitness tracker are you using?
      placeholder: v1.0.0, latest commit hash, etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
